### ISSUE TITLE
老哥已经转行做C#了吗？

### ISSUE THREAD

**Issue by bournes** [zhangqi-ulua/UploadFilesToServerTools#1]
老哥已经转行做C#了吗？JAVA还做吗？

**Comment by zhangqi-ulua** [comment]
啊？？编程是我自己的爱好，java和C#等语言我都会用的，不存在转行不转行。开发什么更适合用什么开发，我就用什么哈

**Comment by zhangqi-ulua** [comment]
啊？？编程是我自己的爱好，java和C#等语言我都会用的，不存在转行不转行。开发什么更适合用什么开发，我就用什么哈
